package com.example;

import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;

@WebServlet("/devops")
public class DevOpsServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws IOException {

        response.setContentType("text/html;charset=UTF-8");

        try (PrintWriter out = response.getWriter()) {
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("    <title>DevOps - Tools & Practices</title>");
            out.println("    <style>");
            out.println("        * { margin: 0; padding: 0; box-sizing: border-box; }");
            out.println("        body {");
            out.println("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;");
            out.println("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);");
            out.println("            min-height: 100vh;");
            out.println("        }");
            out.println("        .navbar {");
            out.println("            background: rgba(255,255,255,0.95);");
            out.println("            padding: 1rem 2rem;");
            out.println("            box-shadow: 0 2px 10px rgba(0,0,0,0.1);");
            out.println("            display: flex;");
            out.println("            justify-content: space-between;");
            out.println("            align-items: center;");
            out.println("        }");
            out.println("        .logo { font-size: 1.5rem; font-weight: bold; color: #667eea; }");
            out.println("        .nav-menu { display: flex; list-style: none; gap: 2rem; }");
            out.println("        .nav-menu a {");
            out.println("            text-decoration: none;");
            out.println("            color: #333;");
            out.println("            font-weight: 500;");
            out.println("            padding: 0.5rem 1rem;");
            out.println("            border-radius: 5px;");
            out.println("            transition: all 0.3s;");
            out.println("        }");
            out.println("        .nav-menu a:hover { color: #667eea; background: #f0f0f0; }");
            out.println("        .container { max-width: 1200px; margin: 2rem auto; padding: 2rem; }");
            out.println("        .card {");
            out.println("            background: white;");
            out.println("            border-radius: 15px;");
            out.println("            padding: 2rem;");
            out.println("            margin-bottom: 2rem;");
            out.println("            box-shadow: 0 10px 30px rgba(0,0,0,0.1);");
            out.println("            transition: transform 0.3s;");
            out.println("        }");
            out.println("        .card:hover { transform: translateY(-5px); }");
            out.println("        h1 { color: #667eea; margin-bottom: 1rem; }");
            out.println("        h2 { color: #764ba2; margin: 1.5rem 0 1rem 0; }");
            out.println("        .tools-grid {");
            out.println("            display: grid;");
            out.println("            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));");
            out.println("            gap: 1.5rem;");
            out.println("            margin-top: 1rem;");
            out.println("        }");
            out.println("        .tool-card {");
            out.println("            background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);");
            out.println("            padding: 1.5rem;");
            out.println("            border-radius: 10px;");
            out.println("            border-left: 4px solid #667eea;");
            out.println("        }");
            out.println("        .tool-icon { font-size: 2rem; margin-bottom: 1rem; }");
            out.println("        .pipeline-stage {");
            out.println("            display: flex;");
            out.println("            align-items: center;");
            out.println("            margin: 1rem 0;");
            out.println("            padding: 1rem;");
            out.println("            background: #f8f9fa;");
            out.println("            border-radius: 8px;");
            out.println("        }");
            out.println("        .stage-status {");
            out.println("            width: 40px;");
            out.println("            height: 40px;");
            out.println("            border-radius: 50%;");
            out.println("            background: #4caf50;");
            out.println("            color: white;");
            out.println("            display: flex;");
            out.println("            align-items: center;");
            out.println("            justify-content: center;");
            out.println("            margin-right: 1rem;");
            out.println("            font-weight: bold;");
            out.println("        }");
            out.println("        .stage-info { flex: 1; }");
            out.println("        .stage-name { font-weight: bold; }");
            out.println("        .badge {");
            out.println("            display: inline-block;");
            out.println("            padding: 0.25rem 0.5rem;");
            out.println("            border-radius: 12px;");
            out.println("            font-size: 0.75rem;");
            out.println("            background: #4caf50;");
            out.println("            color: white;");
            out.println("            margin-left: 0.5rem;");
            out.println("        }");
            out.println("        @keyframes fadeIn {");
            out.println("            from { opacity: 0; transform: translateY(20px); }");
            out.println("            to { opacity: 1; transform: translateY(0); }");
            out.println("        }");
            out.println("        .fade-in { animation: fadeIn 0.6s ease-out; }");
            out.println("    </style>");
            out.println("</head>");
            out.println("<body>");
            out.println("    <nav class=\"navbar\">");
            out.println("        <div class=\"logo\">🚀 DevOps Dashboard</div>");
            out.println("        <ul class=\"nav-menu\">");
            out.println("            <li><a href=\"index.html\">🏠 Home</a></li>");
            out.println("            <li><a href=\"devops\">⚙️ DevOps</a></li>");
            out.println("            <li><a href=\"hello\">📊 Dashboard</a></li>");
            out.println("        </ul>");
            out.println("    </nav>");
            out.println("    <div class=\"container\">");
            out.println("        <div class=\"card fade-in\">");
            out.println("            <h1>⚙️ DevOps Engineering</h1>");
            out.println("            <p>Comprehensive DevOps practices, tools, and CI/CD pipeline management</p>");
            out.println("        </div>");
            out.println("        ");
            out.println("        <div class=\"card fade-in\">");
            out.println("            <h2>🔄 CI/CD Pipeline</h2>");
            out.println("            <div class=\"pipeline-stage\">");
            out.println("                <div class=\"stage-status\">✓</div>");
            out.println("                <div class=\"stage-info\">");
            out.println("                    <div class=\"stage-name\">Code Commit <span class=\"badge\">Git</span></div>");
            out.println("                    <div>Version control with Git workflow</div>");
            out.println("                </div>");
            out.println("            </div>");
            out.println("            <div class=\"pipeline-stage\">");
            out.println("                <div class=\"stage-status\">✓</div>");
            out.println("                <div class=\"stage-info\">");
            out.println("                    <div class=\"stage-name\">Build <span class=\"badge\">Maven</span></div>");
            out.println("                    <div>Automated build and dependency management</div>");
            out.println("                </div>");
            out.println("            </div>");
            out.println("            <div class=\"pipeline-stage\">");
            out.println("                <div class=\"stage-status\">✓</div>");
            out.println("                <div class=\"stage-info\">");
            out.println("                    <div class=\"stage-name\">Test <span class=\"badge\">JUnit</span></div>");
            out.println("                    <div>Unit and integration testing</div>");
            out.println("                </div>");
            out.println("            </div>");
            out.println("            <div class=\"pipeline-stage\">");
            out.println("                <div class=\"stage-status\">✓</div>");
            out.println("                <div class=\"stage-info\">");
            out.println("                    <div class=\"stage-name\">Deploy <span class=\"badge\">K8s</span></div>");
            out.println("                    <div>Container orchestration with Kubernetes</div>");
            out.println("                </div>");
            out.println("            </div>");
            out.println("        </div>");
            out.println("        ");
            out.println("        <div class=\"card fade-in\">");
            out.println("            <h2>🛠️ DevOps Tools & Technologies</h2>");
            out.println("            <div class=\"tools-grid\">");
            out.println("                <div class=\"tool-card\"><div class=\"tool-icon\">📦</div><h3>Version Control</h3><p>Git, GitHub, GitLab, Bitbucket</p></div>");
            out.println("                <div class=\"tool-card\"><div class=\"tool-icon\">🏗️</div><h3>CI/CD</h3><p>Jenkins, GitLab CI, GitHub Actions</p></div>");
            out.println("                <div class=\"tool-card\"><div class=\"tool-icon\">🐳</div><h3>Container</h3><p>Docker, Podman, Container Registry</p></div>");
            out.println("                <div class=\"tool-card\"><div class=\"tool-icon\">☸️</div><h3>Orchestration</h3><p>Kubernetes, OpenShift, EKS</p></div>");
            out.println("                <div class=\"tool-card\"><div class=\"tool-icon\">📊</div><h3>Monitoring</h3><p>Prometheus, Grafana, ELK Stack</p></div>");
            out.println("                <div class=\"tool-card\"><div class=\"tool-icon\">🔧</div><h3>IaC</h3><p>Terraform, Ansible, Pulumi</p></div>");
            out.println("            </div>");
            out.println("        </div>");
            out.println("        ");
            out.println("        <div class=\"card fade-in\">");
            out.println("            <h2>📈 Key Metrics</h2>");
            out.println("            <div class=\"tools-grid\">");
            out.println("                <div class=\"tool-card\"><div class=\"tool-icon\">⚡</div><h3>Deployment Frequency</h3><p style=\"font-size: 1.5rem; font-weight: bold;\">15x/day</p></div>");
            out.println("                <div class=\"tool-card\"><div class=\"tool-icon\">⏱️</div><h3>Lead Time</h3><p style=\"font-size: 1.5rem; font-weight: bold;\">&lt;1 hour</p></div>");
            out.println("                <div class=\"tool-card\"><div class=\"tool-icon\">🔄</div><h3>MTTR</h3><p style=\"font-size: 1.5rem; font-weight: bold;\">&lt;30 min</p></div>");
            out.println("                <div class=\"tool-card\"><div class=\"tool-icon\">❌</div><h3>Failure Rate</h3><p style=\"font-size: 1.5rem; font-weight: bold;\">2-5%</p></div>");
            out.println("            </div>");
            out.println("        </div>");
            out.println("    </div>");
            out.println("</body>");
            out.println("</html>");
        }
    }
}
